### ISSUE TITLE
Small fixes proposal

### ISSUE THREAD

**Issue by iss000** [6502Nerd/dflat#3]
Just some small details which need fix after last commit:
- the binary ROM images are not updated (i.e. they are compiled before the last changes);
- add [printer_out.txt](https://github.com/6502Nerd/dflat/blob/Oric/Oric-DFLAT/emulator/printer_out.txt) to .gitignore - you don't want to share its content ;).

**Comment by 6502Nerd** [comment]
Thanks for pointing this out - did not realise!

**Comment by 6502Nerd** [comment]
Strange - I just downloaded the ROM from GitHub and compared with the last build on my laptop, they are the same?

**Comment by iss000** [comment]
When I compile commit: 708b3475bbc18a9b43c6fd978384e6d7b7e25468 the resulting dflat.rom is different from the one in the emulator/roms/ directory. And when I compared both binaries it seamed that in the emulator/roms/dflat.rom the function 'sgn' was missing, so I've concluded that the file is not from the last committed sources.
Now with commit 6d003c3ffd2d0fe6cddc1d937fab36a81481a10e everything is fine! :)

**Comment by 6502Nerd** [comment]
Thank you for being connected with this and helping to keep it consistent.

**Comment by iss000** [comment]
Hi! I think the binaries (dflat.rom, bank0.bin) are older than sources?
After last comit dfb14010af0cf652294e4aa187c1602a16e1905b 'KB_CAPSLK=1' is missing. After I added it with new compiled rom the keyboard routine doesn't work in Oricutron anymore :(

**Comment by 6502Nerd** [comment]
Oh dear - I really messed up the last update. I think it is fixed now.
A big problem was that I was assembling to completely wrong folder - I am an idiot!
Checked with Oricutron - working again I think.
Sorry about that - let me know if it's ok now.  All binaries should be up to date now
