### ISSUE TITLE
Galaxy Defender 2023 download

### ISSUE THREAD

**Issue by toncho11** [6502Nerd/dflat#6]
Hi,

Where can I download Galaxy Defender 2023 for Oric Atmos?
Maybe you can publish a release here on github?

**Comment by 6502Nerd** [comment]
Hi - really sorry for the months late reply, I didn't notice the issue until today.. Thanks for your interest, Galaxy defender is the file INV3D.TAP in the games folder of the software directory in this repo.  You can load this up in Oricutron - simply fire up this emulator and then under settings (F1) you pick the tape file location and find this file.  Then in dflat type:
`tload "inv3d.tap"`
The game takes a while to load but autostarts once done.
